nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/hbrombeer/ui-extension-latitudesh/gh-pages/extensions/latitudesh/0.1.2
  compressedEndpoint: >-
    https://raw.githubusercontent.com/hbrombeer/ui-extension-latitudesh/gh-pages/extensions/latitudesh/0.1.2.tgz
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/certified: partner
    catalog.cattle.io/display-name: Latitude.sh
    catalog.cattle.io/kube-version: ">= 1.16.0-0"
    catalog.cattle.io/rancher-version: ">= 2.9.0-0"
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
